HSLdevcom/jore4-flux

README.md
crd/flux-crd.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/7)

Upgrade Flux to 0.13.2

---

clusters/playg/flux-sync.yaml
clusters/playg/jore4-env-patch.yaml
clusters/playg/jore4-ingress-patch.yaml
clusters/playg/jore4-secret-keyvaults-patch.yaml
clusters/playg/jore4-secret-mounts-patch.yaml
clusters/playg/kustomization.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/8)

Add playg stage to cluster definitions

---

.github/workflows/test-kustomize.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/9)

Pin audited versions for github actions

---

.github/workflows/test-e2e-cluster-setup.yml
README.md
clusters/e2e/jore4-env-patch.yaml
clusters/e2e/jore4-ingress-patch.yaml
clusters/e2e/kustomization.yaml
kind-cluster.yaml
kindcluster.sh
kubernetes.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/5)

Set up e2e cluster in Kind

---

.github/workflows/test-kustomize.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/10)

Refactor kustomize github workflow to directly use kustomize executable

---

.github/workflows/test-e2e-cluster-setup.yml
README.md
remotecluster.sh

Closes https://github.com/HSLdevcom/jore4/issues/311
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/11)

Setting up e2e cluster remotely

---

.github/workflows/super-linter.yml
development.sh

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/15)

Upgrade super-linter to v4

---

clusters/base/jore4-secret-bindings/jore4-secret-mappings.yaml
clusters/base/jore4-secret-bindings/kustomization.yaml
clusters/base/jore4-services/jore4-auth.yaml
clusters/base/jore4-services/jore4-frontend.yaml
clusters/base/jore4-services/jore4-ingress.yaml
clusters/base/jore4-services/kustomization.yaml
clusters/dev/jore4-env-patch.yaml
clusters/dev/jore4-secrets-patch.yaml
clusters/e2e/jore4-env-patch.yaml
clusters/e2e/jore4-ingress-patch.yaml
clusters/e2e/jore4-local-secrets.yaml
clusters/e2e/jore4-secrets-patch.yaml
clusters/e2e/kustomization.yaml
clusters/playg/jore4-env-patch.yaml
clusters/playg/jore4-secrets-patch.yaml
clusters/prod/jore4-env-patch.yaml
clusters/prod/jore4-secrets-patch.yaml
clusters/test/jore4-env-patch.yaml
clusters/test/jore4-secrets-patch.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/18)

Add auth backend to Kind cluster and Azure clusters

---

clusters/dev/jore4-auth.yaml
clusters/dev/jore4-hasura.yaml
clusters/dev/jore4-limit-range.yaml
clusters/e2e/jore4-auth.yaml
clusters/e2e/jore4-hasura.yaml
clusters/e2e/jore4-limit-range.yaml
clusters/playg/jore4-auth.yaml
clusters/playg/jore4-hasura.yaml
clusters/playg/jore4-limit-range.yaml
clusters/prod/jore4-auth.yaml
clusters/prod/jore4-hasura.yaml
clusters/prod/jore4-limit-range.yaml
clusters/test/jore4-auth.yaml
clusters/test/jore4-hasura.yaml
clusters/test/jore4-limit-range.yaml
generate/values/common.yaml
generate/values/prod.yaml

Beware that the docker image tags contained in this change will need to be updated before integration into the main branch.
Currently the docker tags contained are only the build tags from the referenced repositories PR-branches. After those PRs are integrated into their respective main branches, the docker tags of the main branch build should be used in the flux configuration.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/26)

Deploy auth backend hasura authorization hook

---

clusters/e2e/jore4-auth.yaml
clusters/e2e/jore4-hasura.yaml
generate/values/e2e.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/28)

Fix for secrets in auth backend and hasura in e2e stage

---

.github/workflows/doctoc.yml
.github/workflows/generate-yaml.yml
.github/workflows/super-linter.yml
.github/workflows/test-e2e-cluster-setup.yml
.github/workflows/test-kustomize.yml
clusters/e2e/jore4-limit-range.yaml
generate/values/e2e.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/29)

Kind CI fixes

---

clusters/e2e/jore4-auth.yaml
clusters/e2e/jore4-hasura.yaml
clusters/e2e/jore4-ingress.yaml
generate/templates/kubernetes-all/jore4-ingress.yaml
generate/values/dev.yaml
generate/values/e2e.yaml
generate/values/playg.yaml
generate/values/prod.yaml
generate/values/test.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/30)

Kind cluster CI fixes

---

.github/workflows/test-e2e-docker-compose.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/32)

Fix docker-compose CI test

---

.github/workflows/test-e2e-cluster-setup.yml
.github/workflows/test-e2e-docker-compose.yml
clusters/dev/jore4-ingress.yaml
clusters/dev/jore4-mbtiles.yaml
clusters/dev/kustomization.yaml
clusters/docker-compose/docker-compose.yml
clusters/docker-compose/nginx.conf
clusters/e2e/jore4-ingress.yaml
clusters/e2e/jore4-mbtiles.yaml
clusters/e2e/kustomization.yaml
clusters/playg/jore4-ingress.yaml
clusters/playg/jore4-mbtiles.yaml
clusters/playg/kustomization.yaml
clusters/prod/jore4-ingress.yaml
clusters/prod/jore4-mbtiles.yaml
clusters/prod/kustomization.yaml
clusters/test/jore4-ingress.yaml
clusters/test/jore4-mbtiles.yaml
clusters/test/kustomization.yaml
generate/templates/kubernetes-all/jore4-mbtiles.yaml
generate/values/common.yaml
generate/values/dev.yaml
generate/values/e2e.yaml
generate/values/playg.yaml
generate/values/prod.yaml
generate/values/test.yaml
remotecluster.sh

Fixes https://github.com/HSLdevcom/jore4/issues/446
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/33)

Deploy `jore4-mbtiles-server`

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/31)

Add microservice deployment instructions

---

clusters/dev/jore4-mbtiles.yaml
clusters/dev/jore4-ui.yaml
clusters/docker-compose/docker-compose.yml
clusters/e2e/jore4-mbtiles.yaml
clusters/e2e/jore4-ui.yaml
clusters/playg/jore4-mbtiles.yaml
clusters/playg/jore4-ui.yaml
clusters/prod/jore4-mbtiles.yaml
clusters/prod/jore4-ui.yaml
clusters/test/jore4-mbtiles.yaml
clusters/test/jore4-ui.yaml
generate/values/common.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/35)

Update mbtiles-server and ui images to latest versions

---

.github/workflows/test-e2e-action.yml
README.md
github-actions/setup-e2e-environment/action.yml

setup-e2e-environment/action starts environment with docker-compose and then checks that all services are running. Specific versions for services can be defined with inputs to action.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/42)

Action.yml for setting up docker-compose environment

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/47)

fix to readme and additional check to action.yml from auth repo

---

github-actions/setup-e2e-environment/action.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/49)

additional check for auth backend

---

clusters/dev/jore4-hasura.yaml
clusters/docker-compose/docker-compose.yml
clusters/playg/jore4-hasura.yaml
clusters/prod/jore4-hasura.yaml
clusters/test/jore4-hasura.yaml
generate/values/common.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/48)

Deploy Hasura traffic line feature

---

README.md
clusters/dev/jore4-mapmatching.yaml
clusters/dev/jore4-mapmatchingdb.yaml
clusters/docker-compose/docker-compose.yml
clusters/playg/jore4-mapmatching.yaml
clusters/playg/jore4-mapmatchingdb.yaml
clusters/prod/jore4-mapmatching.yaml
clusters/prod/jore4-mapmatchingdb.yaml
clusters/test/jore4-mapmatching.yaml
clusters/test/jore4-mapmatchingdb.yaml
generate/values/common.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/52)

Update map-matching service.

---

clusters/dev/jore4-mapmatching.yaml
clusters/docker-compose/docker-compose.yml
clusters/playg/jore4-mapmatching.yaml
clusters/prod/jore4-mapmatching.yaml
clusters/test/jore4-mapmatching.yaml
generate/values/common.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/53)

Update map-matching service with a landing page.

---

clusters/docker-compose/docker-compose.yml
generate/values/e2e.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/54)

Update azuredbmock in e2e (docker-compose) env

---

clusters/dev/jore4-hasura.yaml
clusters/docker-compose/docker-compose.yml
clusters/playg/jore4-hasura.yaml
clusters/prod/jore4-hasura.yaml
clusters/test/jore4-hasura.yaml
generate/values/common.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/55)

Update Hasura (validity periods and priorities)

---

clusters/dev/jore4-ui.yaml
clusters/docker-compose/docker-compose.yml
clusters/playg/jore4-ui.yaml
clusters/prod/jore4-ui.yaml
clusters/test/jore4-ui.yaml
generate/values/common.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/56)

Update UI (create new line)

---

clusters/dev/jore4-hasura.yaml
clusters/docker-compose/docker-compose.yml
clusters/playg/jore4-hasura.yaml
clusters/prod/jore4-hasura.yaml
clusters/test/jore4-hasura.yaml
generate/values/common.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/57)

Update Hasura (fix migrations)

---

.github/workflows/test-e2e-action.yml
github-actions/setup-e2e-environment/action.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/58)

Allow setting map-matching service and db versions in e2e setup action

---

clusters/dev/jore4-auth.yaml
clusters/docker-compose/docker-compose.yml
clusters/playg/jore4-auth.yaml
clusters/prod/jore4-auth.yaml
clusters/test/jore4-auth.yaml
generate/values/common.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/59)

Deploy jore4-auth updates (session fixes)

---

clusters/dev/jore4-hasura.yaml
clusters/dev/jore4-mapmatching.yaml
clusters/dev/jore4-mapmatchingdb.yaml
clusters/dev/jore4-mbtiles.yaml
clusters/dev/jore4-ui.yaml
clusters/docker-compose/docker-compose.yml
clusters/playg/jore4-hasura.yaml
clusters/playg/jore4-mapmatching.yaml
clusters/playg/jore4-mapmatchingdb.yaml
clusters/playg/jore4-mbtiles.yaml
clusters/playg/jore4-ui.yaml
clusters/prod/jore4-hasura.yaml
clusters/prod/jore4-mapmatching.yaml
clusters/prod/jore4-mapmatchingdb.yaml
clusters/prod/jore4-mbtiles.yaml
clusters/prod/jore4-ui.yaml
clusters/test/jore4-hasura.yaml
clusters/test/jore4-mapmatching.yaml
clusters/test/jore4-mapmatchingdb.yaml
clusters/test/jore4-mbtiles.yaml
clusters/test/jore4-ui.yaml
generate/values/common.yaml
generate/values/e2e.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/82)

Update all microservices to their latest versions

---

.github/workflows/test-e2e-docker-compose.yml
clusters/dev/jore4-ingress.yaml
clusters/docker-compose/nginx.conf
clusters/playg/jore4-ingress.yaml
clusters/prod/jore4-ingress.yaml
clusters/test/jore4-ingress.yaml
generate/values/dev.yaml
generate/values/e2e.yaml
generate/values/playg.yaml
generate/values/prod.yaml
generate/values/test.yaml
github-actions/setup-e2e-environment/action.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/88)

Fix ingress to use /route path for map-matching microservice

---

.github/workflows/test-e2e-docker-compose.yml
clusters/dev/jore4-ingress.yaml
clusters/docker-compose/nginx.conf
clusters/playg/jore4-ingress.yaml
clusters/prod/jore4-ingress.yaml
clusters/test/jore4-ingress.yaml
generate/values/dev.yaml
generate/values/e2e.yaml
generate/values/playg.yaml
generate/values/prod.yaml
generate/values/test.yaml
github-actions/setup-e2e-environment/action.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/89)

Revert mapmatching ingress path to /api/mapmatching

---

.github/workflows/test-e2e-action.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/96)

Fix e2e setup test

---

.github/workflows/auto-update.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/147)

Fix invalid reference to tibdex/github-app-token github action

---

.github/workflows/auto-update.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/161)

Use HSL specific Hasura image

---

clusters/dev/jore4-hasura.yaml
clusters/dev/jore4-ui.yaml
clusters/docker-compose/docker-compose.yml
clusters/playg/jore4-hasura.yaml
clusters/playg/jore4-ui.yaml
clusters/prod/jore4-hasura.yaml
clusters/prod/jore4-ui.yaml
clusters/test/jore4-hasura.yaml
clusters/test/jore4-ui.yaml
generate/values/common.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/189)

Update hasura and UI versions to include localization

---

.github/workflows/run-e2e-tests.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/190)

Run e2e tests for the docker-compose bundle

---

.github/workflows/run-e2e-tests.yml
github-actions/setup-e2e-environment/action.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/203)

Only run e2e tests with auto-deploy pull requests 

---

clusters/dev/jore4-hasura.yaml
clusters/dev/jore4-ui.yaml
clusters/docker-compose/docker-compose.yml
clusters/playg/jore4-hasura.yaml
clusters/playg/jore4-ui.yaml
clusters/prod/jore4-hasura.yaml
clusters/prod/jore4-ui.yaml
clusters/test/jore4-hasura.yaml
clusters/test/jore4-ui.yaml
generate/values/common.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/226)

Refactor stop ref to label

---

.github/workflows/auto-update.yml
.github/workflows/test-e2e-action.yml
clusters/dev/jore4-hasura.yaml
clusters/dev/jore4-jore3importer.yaml
clusters/dev/jore4-ui.yaml
clusters/docker-compose/docker-compose.yml
clusters/playg/jore4-hasura.yaml
clusters/playg/jore4-jore3importer.yaml
clusters/playg/jore4-ui.yaml
clusters/prod/jore4-hasura.yaml
clusters/prod/jore4-jore3importer.yaml
clusters/prod/jore4-ui.yaml
clusters/test/jore4-hasura.yaml
clusters/test/jore4-jore3importer.yaml
clusters/test/jore4-ui.yaml
generate/values/common.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/227)

Stop label

---

clusters/dev/jore4-mapmatchingdb.yaml
clusters/docker-compose/docker-compose.yml
clusters/playg/jore4-mapmatchingdb.yaml
clusters/prod/jore4-mapmatchingdb.yaml
clusters/test/jore4-mapmatchingdb.yaml
generate/values/common.yaml

Handover version - with changes from QGIS fix layers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/229)

Update database dump for map-matching-service: 2022-06-09

---

clusters/dev/jore4-ui.yaml
clusters/docker-compose/docker-compose.yml
clusters/playg/jore4-ui.yaml
clusters/prod/jore4-ui.yaml
clusters/test/jore4-ui.yaml
generate/values/common.yaml

This pull request was generated by [JORE4 auto-update workflow](https://github.com/HSLdevcom/jore4-flux/actions/workflows/auto-update.yml).
```diff
- Note: Should merge this pull request instead of rebasing it.
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/256)

Auto-deploy to dev

---

clusters/dev/jore4-mbtiles.yaml
clusters/docker-compose/docker-compose.yml
clusters/playg/jore4-mbtiles.yaml
clusters/prod/jore4-mbtiles.yaml
clusters/test/jore4-mbtiles.yaml
generate/values/common.yaml

Resolves HSLdevcom/jore4#848
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/262)

Update digiroad infra vector tiles to latest version

---

clusters/docker-compose/docker-compose.yml
generate/values/e2e.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/354)

Update testdb image to include timetables database

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/hsldevcom/jore4-flux/429)

Update README E2E docker-compose download script for private flux repo
